//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHandyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerRequestFor { get; set; }
        public Nullable<System.DateTime> CustomerDayTimePref { get; set; }
        public string CustomerAdditionalInfo { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CustomerDateTimePrefText { get; set; }
        public string Area { get; set; }
        public Nullable<int> City { get; set; }
    }
}
