//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHandyService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HandyBackOfficeEntities : DbContext
    {
        public HandyBackOfficeEntities()
            : base("name=HandyBackOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreaInCity> AreaInCities { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CustomerRequest> CustomerRequests { get; set; }
    }
}
